export const cartTypes = {
    GET_CART_LIST_REQUEST: 'GET_CART_LIST_REQUEST',
    GET_CART_LIST_SUCCESS: 'GET_CART_LIST_SUCCESS',
    GET_CART_LIST_FAILURE: 'GET_CART_LIST_FAILURE',

    ADD_TO_CART_REQUEST: 'ADD_TO_CART_REQUEST',
    ADD_TO_CART_SUCCESS: 'ADD_TO_CART_SUCCESS',
    ADD_TO_CART_FAILURE: 'ADD_TO_CART_FAILURE',
};
