export const homeTypes = {
    GET_CAR_COLLECTION_REQUEST: 'GET_CAR_COLLECTION_REQUEST',
    GET_CAR_COLLECTION_SUCCESS: 'GET_CAR_COLLECTION_SUCCESS',
    GET_CAR_COLLECTION_FAILURE: 'GET_CAR_COLLECTION_FAILURE',
};
