export const GET_CAR_COLLECTION_REQUEST = "GET_CAR_COLLECTION_REQUEST";
export const GET_CAR_COLLECTION_SUCCESS = "GET_CAR_COLLECTION_SUCCESS";
export const GET_CAR_COLLECTION_FAILURE = "GET_CAR_COLLECTION_FAILURE";